version: '3.8'

services:
  obvi_slam:
    build: .
    image: obvi_slam_custom
    container_name: obvi_slam_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../src/:/root/external/ut_vslam/src
      - ../scripts:/root/scripts
      - ../include/:/root/external/ut_vslam/include
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../data:/root/full_data
      - ../original_data:/root/data
      - ../config:/root/external/ut_vslam/config
      - ../build_cache:/root/external/ut_vslam/build
    stdin_open: true
    tty: true
    command: /bin/bash -c "/usr/local/bin/run_pipeline.sh"